const ADD_POST = "ADD_POST";
const REQUEST_POSTS = "REQUEST_POSTS";
const RECEIVE_POSTS = "RECEIVE_POSTS";

const REQUEST_LOGIN = "REQUEST_LOGIN";
const FETCH_LOGIN = "FETCH_LOGIN";
const RECEIVE_LOGIN = "RECEIVE_LOGIN";

const REQUEST_ORDERS = "REQUEST_ORDERS";
const FETCH_ORDERS = "FETCH_ORDERS";
const RECEIVE_ORDERS = "RECEIVE_ORDERS";

export {
  ADD_POST,
  REQUEST_POSTS,
  RECEIVE_POSTS,
  REQUEST_LOGIN,
  RECEIVE_LOGIN,
  REQUEST_ORDERS,
  FETCH_ORDERS,
  RECEIVE_ORDERS,
  FETCH_LOGIN
};
